base/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sponsors/', views.sponsors, name='sponsors'),
    url(r'^team/', views.team, name='team'),
]

incident/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
	url(r'', include('base.urls', namespace='base')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.core.validators import RegexValidator
from django.db import models

# Create your models here.

class Team(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name

class TeamMember(models.Model):
	team = models.ForeignKey(Team, on_delete=models.CASCADE, default='1')
	name = models.CharField(max_length=50)
	post = models.CharField(max_length=50)
	email = models.EmailField()
	image = models.ImageField(upload_to= 'teamimages/')
	phone_number = models.CharField(max_length=10, validators=[
    	RegexValidator(regex=r'^[7-9][0-9]*$')
    		])

	def __str__(self):
		return self.name

base/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Team, TeamMember

def index(request):
	return render(request, 'base/home.html')

def team(request):
	teams = Team.objects.all().order_by('name')
	context = { 'teams' : teams }
	return render(request, 'base/team.html', context)

def sponsors(request):
	return render(request, 'base/sponsors.html')

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Website for Incident 2018">
    <meta name="author" content="Samyak R Jain, Ananda Rao">

    <title>Incident 2018</title>

    <link rel="shortcut icon" href="{% static 'images/inci-logo.png' %}">

    <!-- Stylesheet -->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">

    {% block head %}  <!-- head block starts here -->               
                 
    {% endblock %} <!-- head block ends here -->
</head>

  <body>

    <!-- Navbar -->

    <div class="divnav">  
      <nav class="navbar navbar-default bg-info" role="navigation">
        <div class="navbar-header ">
          <!-- <a href="#">Contact Us</a> -->
          <a class="navbar-brand" href="#">Incident '18</a>
          <!-- <a href="#">Sponsors</a> -->
        </div>
      </nav>
    </div>
    
    <!-- Scripts -->


    {% block body %}

    {% endblock %}

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

    <!-- <script type="text/javascript">
      (function ($) {
        $(document).ready(function(){
          
        // hide .navbar first
        $(".navbar").hide();
        
        // fade in .navbar
        $(function () {
          $(window).scroll(function () {
                  // set distance user needs to scroll before we fadeIn navbar
            if ($(this).scrollTop() > 100) {
              $('.navbar').fadeIn();
            } else {
              $('.navbar').fadeOut();
            }
          });

        
        });

      });
        }(jQuery));

    </script> -->

    {% block scripts %}

    {% endblock %}

  </body>
</html>

base/templates/base/sponsors.html
{% extends 'base/base.html' %}

{% load static %}

{% block body_block %}
    <div class="v ai l">
      <div class="bz">
        <img src="{% static 'images/psponsors.png' %}" alt="">
      </div>
      <div class="header-wrapper c valign-wrapper">
        <div class="d jt offset-s2 ci">
          <h1>PREVIOUS SPONSORS</h1>
          <span class="dx">And many more!</span>
        </div>
      </div>
    </div>
    <div class="v ai l">
      <div class="bz">
        <img src="" alt="">
      </div>
      <div class="header-wrapper c valign-wrapper">
        <div class="d jt offset-s2 ci">
          <h1>PRESENT SPONSORS</h1>
          <span class="dx">Coming Soon!</span>
        </div>
      </div>
    </div>
{% endblock %}

base/templates/base/team.html
{% extends 'base/base.html' %}

{% load static %}
{% block body_block %}
    <div class="v ai l">
      <div class="bz">
        <img src="{% static 'images/team.jpg' %}" alt="">
      </div>
      <div class="header-wrapper c valign-wrapper">
        <div class="d jt offset-s2 ci">
          <h1>Team!</h1>
          <span class="dx">Founded in 2015, we strive to be the best at what we do. This is made possible by our amazing team located around the world.</span>
        </div>
      </div>
    </div>

    <div class="v l full-height">
      <div class="c ci">
        <div class="d iv jc offset-m1 cy">

        {% for team in teams %}

          <div class="c">
            <div class="d iv ki center-on-small-only">
              <h3 class="section-title">{{ team.name }}</h3>
            </div>

            <div class="d iv km">
              <div class="c">

                {% for teammember in team.teammember_set.all %}
                <div class="d iv kr">
                  <div class="avatar-wrapper">
                    <span class="k">
                      <img src="{{ teammember.image.url }}" alt="">
                    </span>
                  </div>
                  <div class="avatar-name">
                    <span class="fx">{{teammember.name}}</span>
                    <span class="cx">{{teammember.post}}</span>
                    <span class="cx">{{teammember.email}}</span>
                    <span class="cx">{{teammember.phone_number}}</span>
                  </div>
                </div>

                {% endfor %}
              </div>
            </div>
          </div>

        {% endfor %}
        </div>
      </div>
    </div>

{% endblock %}